# Nginx como entrada unica y balanceador de carga. Semana 7.
# Paso 4 del laboratorio  agregar la segunda replica en el bloque upstream.

upstream api {
    # max_fails=1 fail_timeout=10s  si una replica falla una vez, se la saca del reparto por 10 s
    server api1:8000 max_fails=1 fail_timeout=10s;
    server api2:8000 max_fails=1 fail_timeout=10s;      # <- Paso 4, quitar el comentario
}

server {
    listen 80;

    location / {
        proxy_pass http://api;
        proxy_connect_timeout 1s;                 # si la replica no contesta en 1 s, se prueba la otra
        proxy_read_timeout 10s;
        proxy_next_upstream error timeout;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header X-Atendido-Por $upstream_addr always;
    }
}
